services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    build:
      dockerfilePath: Dockerfile
      context: .
    ports:
      - 80
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
    healthCheckPath: /
